// Generated by Airbus KMS Server (which does consider UID to be used as a string, not raw hex)
#define AIRBUS_KEYMAT_KPAK                                                                                                                 \
    "0450d4670bde75244f28d2838a0d25558a7a72686d4522d4c8273fb6442aebfa93dbdd37551afd263b5dfd617f3960c65a8c298850ff99f20366dce7d4367217f4"
#define AIRBUS_KEYMAT_Z                                                                                                                    \
    "045958EF1B1679BF099B3A030DF255AA6A23C1D8F143D4D23F753E69BD27A832F38CB4AD53DDEF4260B0FE8BB45C4C1FF510EFFE300367A37B61F701D914AEF09724" \
    "825FA0707D61A6DFF4FBD7273566CDDE352A0B04B7C16A78309BE640697DE747613A5FC195E8B9F328852A579DB8F99B1D0034479EA9C5595F47C4B2F54FF21508D3" \
    "7514DCF7A8E143A6058C09A6BF2C9858CA37C258065AE6BF7532BC8B5B63383866E0753C5AC0E72709F8445F2E6178E065857E0EDA10F68206B63505ED87E534FB28" \
    "31FF957FB7DC619DAE61301EEACC2FDA3680EA4999258A833CEA8FC67C6D19487FB449059F26CC8AAB655AB58B7CC796E24E9A394095754F5F8BAE"
#define AIRBUS_KEYMAT_RSK_GMS                                                                                                              \
    "04991dd025c1bbd553f8bb35e3fd730747116bfd5fce8d952a680a7ee33c81a9793fb109f2ea33804e8e248d56c436c903ccef65b96abae7e555bea4c6f6929ffc18" \
    "8f179f28dfd0fc0fac419871495bfa35cd7f7cb9a8c91a566ae4d359a0efafd53357618f87ce53cefa5a5906e53e8d0864140fb1ad9ee097214780b63aa1084e2da4" \
    "b713ccd42ec7abf967dce69108a4d8ad173553080e8c5972cf9a9d00662b080fbbe4b13dfa46f1ee34e6fbc3eed7c47a9e7382c3f456bdb009f71305f0fb7e5fee32" \
    "d0800707a5a1673271f1234f1c4d4fda52651ada3e292c519d998a9d2463e976df0c9f9c040f2716e2f51b7163b2f9986b176359a70467870c1f04"
#define AIRBUS_KEYMAT_SSK_GMS "c9de2281bb7e7455cc63c95ebb0d576dbfd998b940d9eac71f3915689b83abec"
#define AIRBUS_KEYMAT_PVT_GMS                                                                                                              \
    "049e8c279b4c673515032ac1e8d4ba5e91d3e38fbc9e96da577568cec7d46cbeb1edc62a9bc0bfbec07d832c8a771103d5f00717eadcaf6a420a9d1cdf82e726ec"

#define STW_KEYMAT_KPAK                                                                                                                    \
    "0448f9c2c48b50735f6bc70ec6691073243f1e0bd83cc73bb936d61ffcb2d6049a5b297e8205b29fbd8591cb582d6402add21451ce4beebeaaa7520e93b11cf28f"
#define STW_KEYMAT_Z                                                                                                                       \
    "046fc2cf00fd48467abe7c02f383002fc49b6632bf0f7071d958f1f128154e6fae1f69bb91691a191a358fe647a3e020d2365d52f81fb3af4ea271654f1a880274c1" \
    "ae228ac72cc15d535394321bd2143cea2619fb3b0c6ce7a5f72714d8ef4d11cb0c991c3376ca31b168b01e66021effdbf7920bd66615e6f0d6a1e61c06e72e61b413" \
    "8738c11bc249a3849e9c4cff327a7d0d2769c3d97a37f86adfb13baa257e628ce236f40360d3f7b8d95b0e3fcc19417602d7d6b8928b855eae9129be1f0b87d33e88" \
    "4906dd95a04a8bd61240bad60f9dfada64806726f8f08b86343f54046416f5198116e9798c218bcf9ca07d0baa4be50062bfe54e44495b6ed59cb6"
#define STW_KEYMAT_RSK_GMS                                                                                                                 \
    "046a44726222c64787933859e9677ee36cd1e7bf9fd54593be222132d6239876b7038ca11939ecf4f3df0fc6a88f066e941d78598b4ce8016a0b2590f0f0e2602110" \
    "270071e8704f759ec77dd62b6433dbbb3852d46957c994912c8ccf12b9696b194c1411e32766d4f2d6e9d375eb4a7aefcb63f30706db5379fdff2292fd5abf7da738" \
    "6f365dff97303b55ffeab5bd28bb8fca2a0084144c039da74277c1e6e6de3c42f7b8835e9cce0178215e43fa5a473f9176e4653c3cf38727c86dad8889124c77a739" \
    "b7aeffdc03b56b7f5bf5ea1256bd1920cfbe0786742de77208f9375d35b1c4bc1968733ebef461dd03647abe948442cb87c24e8c1f759120b863be"
#define STW_KEYMAT_SSK_GMS "c11cbdddb39c60592b73c7343501fc451347f46c43a527227132cb0c7b057253"
#define STW_KEYMAT_PVT_GMS                                                                                                                 \
    "047addd25bde0b5c685f8ad22b3291a985ee612c63a6e6ef0b670692a83c88fb7f502e4bdd83428bf4fcc2740c9ec8e0e089f020e0ad72b480478bf87e3514dfde"

#define STW_KEYMAT_RSK_SIPP                                                                                                                \
    "0456d4efe394a871b5d66ce1a81cbcdda11c3b0222db8f6640b883ad785ec9a6f61ee09f9f7d8124986244eccd87713f08029c01f56f2ed159aa3dc4d3c5802ac79e" \
    "a6157dcb1a394606c9e0d3d5df1a22030d0522bac7c5c030a42be8c7f4464245da3e316a213993d7c1ae4be17c3b7db6797204c58eba56d3e4c7ea84aec31586705b" \
    "791a059152cd69713507aa7575a20bf3a19f8c33861ad0045bf73e1e2ee90eef28c2a047d6eb92756d1e4abef8877c4c1a61cfda7c77344f3af4ed5a8418f13a4647" \
    "d88cd0c16338d4f55e0d10fab25343e2bef75987f20651e7ca62704251149506be1fb2ea9c5fd8db577bc03a8ab528851276126edac8016af4c72e"
#define STW_KEYMAT_SSK_SIPP "011259abade5bd12c359c63a66777d46398fbb8378d50dfa58f28545772eccb4"
#define STW_KEYMAT_PVT_SIPP                                                                                                                \
    "048e97457c94ea1e91b85518f0983ad135aeb264bbec3f501fa061cca15a94f9822b49db4f1b45bb7cdf29cf29e1c8233186a336ad7c802097b2f9e4213baded5e"

#define STW_KMS_URI "kms.mydev.streamwide.com";
